# Generated by Django 6.0.7 on 2026-08-09 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Sujet"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("traite", "Traité"),
                            ("annule", "Annulé"),
                        ],
                        default="nouveau",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Identifiant")),
                ("title", models.CharField(max_length=120, verbose_name="Titre")),
                ("short_desc", models.CharField(max_length=255, verbose_name="Résumé")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "icon",
                    models.CharField(
                        default="briefcase", max_length=30, verbose_name="Icône"
                    ),
                ),
                (
                    "price_hint",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Indication tarifaire"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DevisRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Société"
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Budget estimé"
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="Détails")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("en_cours", "En cours"),
                            ("traite", "Traité"),
                            ("annule", "Annulé"),
                        ],
                        default="nouveau",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de devis",
                "verbose_name_plural": "Demandes de devis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("time", models.CharField(max_length=5, verbose_name="Heure")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirme", "Confirmé"),
                            ("en_attente", "En attente"),
                            ("annule", "Annulé"),
                        ],
                        default="confirme",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Demandé le"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["date", "time"],
            },
        ),
    ]
