# Generated by Django 6.0.7 on 2026-08-10 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_client_payment_servicefollowup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="cin",
            field=models.CharField(
                blank=True, max_length=8, verbose_name="Numéro de carte d'identité"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="matricule_fiscale",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Matricule fiscale"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="prenom",
            field=models.CharField(blank=True, max_length=120, verbose_name="Prénom"),
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Compte utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="E-mail"),
        ),
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=64, unique=True, verbose_name="Jeton"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientServiceSuivi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Montant (TND)"
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("paye", "Payé"),
                            ("retard", "En retard / impayé"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut de paiement",
                    ),
                ),
                (
                    "statut_service",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours de traitement"),
                            ("valide", "Validé / déposé / conforme"),
                            ("cloture", "Clôturé"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Suivi du service",
                    ),
                ),
                (
                    "date_echeance",
                    models.DateField(verbose_name="Échéance fiscale / sociale"),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, verbose_name="Notes / remarques (ex : accusé TEJ)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="core.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "type_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.service",
                        verbose_name="Type de service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi & paiement client",
                "verbose_name_plural": "Suivis & paiements clients",
                "ordering": ["date_echeance", "-id"],
            },
        ),
    ]
