# Generated by Django 6.0.7 on 2026-08-10 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_client_cin_client_matricule_fiscale_client_prenom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientservicesuivi",
            name="date_echeance",
            field=models.DateField(
                blank=True, null=True, verbose_name="Échéance fiscale / sociale"
            ),
        ),
        migrations.AlterField(
            model_name="clientservicesuivi",
            name="montant",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=10, verbose_name="Montant (TND)"
            ),
        ),
        migrations.CreateModel(
            name="ClientMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("client", "Client"), ("admin", "Cabinet")],
                        default="client",
                        max_length=10,
                        verbose_name="Émetteur",
                    ),
                ),
                ("text", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Envoyé le"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message client",
                "verbose_name_plural": "Messages clients",
                "ordering": ["created_at"],
            },
        ),
    ]
