# Generated by Django 6.0.7 on 2026-08-10 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_clientservicesuivi_date_echeance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="client",
            name="statut_client",
            field=models.CharField(
                choices=[
                    ("entreprise", "Entreprise"),
                    ("personne_physique", "Personne physique"),
                ],
                default="entreprise",
                max_length=30,
                verbose_name="Type de client",
            ),
        ),
        migrations.AddField(
            model_name="clientservicesuivi",
            name="frequence",
            field=models.CharField(
                choices=[
                    ("ponctuel", "Ponctuel"),
                    ("mensuel", "Mensuel"),
                    ("trimestriel", "Trimestriel"),
                    ("semestriel", "Semestriel"),
                    ("annuel", "Annuel"),
                ],
                default="ponctuel",
                max_length=20,
                verbose_name="Répétition du service",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="company",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Raison sociale"
            ),
        ),
        migrations.AlterField(
            model_name="clientservicesuivi",
            name="montant",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=10, verbose_name="Prix (TND)"
            ),
        ),
        migrations.CreateModel(
            name="DossierAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="attachments/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Type MIME"
                    ),
                ),
                (
                    "size",
                    models.IntegerField(default=0, verbose_name="Taille (octets)"),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        choices=[("client", "Client"), ("admin", "Cabinet")],
                        default="client",
                        max_length=10,
                        verbose_name="Ajouté par",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ajouté le"),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.clientservicesuivi",
                        verbose_name="Dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DossierTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À faire"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                        ],
                        default="a_faire",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_echeance",
                    models.DateField(blank=True, null=True, verbose_name="Échéance"),
                ),
                (
                    "repetition",
                    models.CharField(
                        choices=[
                            ("ponctuel", "Ponctuel"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("semestriel", "Semestriel"),
                            ("annuel", "Annuel"),
                        ],
                        default="ponctuel",
                        max_length=20,
                        verbose_name="Répétition",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.clientservicesuivi",
                        verbose_name="Dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche de dossier",
                "verbose_name_plural": "Tâches de dossiers",
                "ordering": ["date_echeance", "id"],
            },
        ),
        migrations.CreateModel(
            name="Prefacture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=30, unique=True, verbose_name="Numéro"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Montant HT (TND)"
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.0,
                        max_digits=5,
                        verbose_name="Taux TVA (%)",
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Montant TTC (TND)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("emise", "Émise"),
                            ("payee", "Payée"),
                            ("annulee", "Annulée"),
                        ],
                        default="emise",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefactures",
                        to="core.clientservicesuivi",
                        verbose_name="Dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préfacture",
                "verbose_name_plural": "Préfactures",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
