# Generated by Django 6.0.7 on 2026-08-10 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_client_adresse_client_statut_client_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclarationFiscale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_declaration",
                    models.CharField(
                        choices=[
                            ("mensuelle", "Déclaration Mensuelle (TVA / RS)"),
                            ("acompte", "Acompte Provisionnel IS / IRPP"),
                            ("annuelle", "Bilan & Liasse Fiscale Annuelle"),
                            ("autre", "Autre Déclaration Spécifique"),
                        ],
                        max_length=20,
                        verbose_name="Type de déclaration",
                    ),
                ),
                (
                    "periode",
                    models.CharField(
                        max_length=80,
                        verbose_name="Période (ex : Mois de Juillet 2026 / Exercice 2025)",
                    ),
                ),
                (
                    "date_echeance_legale",
                    models.DateField(verbose_name="Date limite légale"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À préparer"),
                            ("en_cours", "En cours de vérification"),
                            ("depose", "Déposé (Validé)"),
                            ("retard", "En retard"),
                        ],
                        default="a_faire",
                        max_length=20,
                        verbose_name="Statut du dossier",
                    ),
                ),
                (
                    "numero_quittance_ou_tej",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="N° quittance / accusé de dépôt",
                    ),
                ),
                (
                    "montant_a_payer",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant net à payer (TND)",
                    ),
                ),
                (
                    "notes_collaborateur",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Remarques internes ou conseils",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations",
                        to="core.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Déclaration fiscale",
                "verbose_name_plural": "Suivi des déclarations fiscales",
                "ordering": ["date_echeance_legale", "-id"],
            },
        ),
    ]
