# Generated by Django 6.0.7 on 2026-08-10 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_declarationfiscale"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicefollowup",
            name="dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_followups",
                to="core.clientservicesuivi",
                verbose_name="Dossier associé",
            ),
        ),
    ]
