# Generated by Django 6.0.7 on 2026-08-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_servicefollowup_dossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientservicesuivi",
            name="service_note",
            field=models.TextField(
                blank=True, verbose_name="Note du service (dans le dossier)"
            ),
        ),
        migrations.AlterField(
            model_name="clientservicesuivi",
            name="commentaire",
            field=models.TextField(blank=True, verbose_name="Note du dossier"),
        ),
    ]
