# Generated by Django 6.0.7 on 2026-08-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_clientservicesuivi_service_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subservices",
                to="core.service",
                verbose_name="Service parent (sous-service)",
            ),
        ),
    ]
