# Generated by Django 6.0.7 on 2026-08-11 00:04

from django.db import migrations


def create_fiscal_subservices(apps, schema_editor):
    Service = apps.get_model("core", "Service")
    try:
        parent = Service.objects.get(slug="tax")
    except Service.DoesNotExist:
        return
    subs = [
        ("mensuelle-tva-rs", "Déclaration mensuelle — TVA & Retenues", "TVA collectée/déductible, retenue à la source et taxes spécifiques (FODEC, TCL) du mois."),
        ("acomptes-is-irpp", "Acomptes provisionnels — IS / IRPP", "Trois échéances annuelles (28 février, 28 juin, 28 septembre) sur la base du bénéfice de l'exercice précédent."),
        ("liasse-fiscale", "Liasse fiscale annuelle — IS / IRPP", "Déclaration annuelle des résultats : bilan, compte de résultat, réintégrations et déductions fiscales."),
    ]
    for slug, title, desc in subs:
        obj, created = Service.objects.get_or_create(
            slug=slug,
            defaults=dict(title=title, short_desc=desc, description=desc, icon="file-text", parent=parent, price_hint=""),
        )
        if not created:
            obj.parent = parent
            obj.save(update_fields=["parent"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_service_parent"),
    ]

    operations = [
        migrations.RunPython(create_fiscal_subservices, migrations.RunPython.noop),
    ]
