# Generated by Django 6.0.7 on 2026-08-11 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_fiscal_subservices"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossiertask",
            name="service_followup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.servicefollowup",
                verbose_name="Suivi de service lié",
            ),
        ),
    ]
