# Generated by Django 6.0.7 on 2026-08-11 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_dossiertask_service_followup"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmessage",
            name="dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="core.clientservicesuivi",
                verbose_name="Dossier lié",
            ),
        ),
        migrations.AddField(
            model_name="clientmessage",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="core.service",
                verbose_name="Service lié",
            ),
        ),
        migrations.AddField(
            model_name="clientmessage",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="core.dossiertask",
                verbose_name="Tâche liée",
            ),
        ),
    ]
